# Generated by Django 4.2.5 on 2023-10-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.UUIDField()),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('tipo', models.CharField(max_length=64)),
            ],
        ),
    ]
