# Generated by Django 4.2.5 on 2023-10-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='date',
            field=models.CharField(max_length=64),
        ),
    ]
