# Generated by Django 4.2.5 on 2023-10-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_despacho__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='_id',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
